if(NOT DEFINED PIKOCODE_TARGET)
    set(PIKOCODE_TARGET ${PROJECT_NAME})
endif()

target_compile_definitions(${PIKOCODE_TARGET} PRIVATE
    WS2812_ENABLED=1
    MIDI_IN_ENABLED=0
    MIDI_RESET_EVERY_BEAT=16
    MIDI_CLOCK_MULTIPLIER=2
    MIDI_NOTE_KEY=0
    PCB_V2_LAYOUT=0
)
